Feat remedial js examples
rangle/angular-training-examples pull request #17
Opened 2016-11-07 18:19 UTC by sinelanguage

connect to #34

2016-11-07 18:20 UTC, sinelanguage commented
I have completed examples for cards #34 to #38 for the remedial Javascript examples.  This PR has all of them

2016-11-08 15:16 UTC, winkerVSbecks commented
I think most of these files you added are using 4 spaces while the rest of the project is using 2 spaces. Would you mind switching to 2 spaces to be consistent. Might be worth adding an `editorconfig`.

2016-11-08 15:17 UTC, winkerVSbecks commented
Sorry I forgot to mention this earlier… could you limit one card to one PR in the future. It just makes it easier to review and manage the project.

2016-11-08 16:19 UTC, winkerVSbecks requested changes

2016-11-08 16:19 UTC, winkerVSbecks commented on language-examples/remedial-js/1.0-http-requests/index.html
> +        <li>initial line, different for request vs. response</li>
Not sure I follow this. What line is this referring to?

2016-11-08 16:19 UTC, winkerVSbecks commented on language-examples/remedial-js/2.0-REST/app/exercise.js
> +router.get('/userlist', function(req, res) {
Love this example which shows back end and front end code. We should probably expand this a bit more by demonstrating the `posts` end point from here: https://jsonplaceholder.typicode.com. That will show a good example of nouns. It could be as simple as a function that makes get requests. Just add comments in the REAMDE for the instructor to demonstrate the various end points.

The exercise can then be to hit the end point with different HTTP verbs. Or query for specific data like posts for userID 1 or comments for post 1, etc.

2016-11-08 16:19 UTC, winkerVSbecks commented on language-examples/remedial-js/5.0-transpiling/README.md
> +# 5.0 - Transpiling
These are great examples! 

One of the things we could capture here is to show the transpiling happening for this example by going to the sources tab:

<img width="925" alt="screen shot 2016-11-08 at 10 21 41 am" src="https://cloud.githubusercontent.com/assets/42671/20104774/382c5890-a59d-11e6-87b7-0ab65a140a2e.png">

For the angular examples you will notice a purpose section in the README. It captures things that the instructor should demonstrate or the intention behind a chapter. You've done a really good job capturing that. I would just make sure to differentiate between purpose and exercise sections by using headings. See this for example: https://github.com/rangle/angular-training-examples/tree/master/src/examples/10.0-two-way-binding

2016-11-08 16:34 UTC, sinelanguage commented on language-examples/remedial-js/1.0-http-requests/index.html
> +        <li>initial line, different for request vs. response</li>
Its referring to "This line" so maybe change it to say:
"This being the first line of the request, depending on the type of request will be different for a GET request vs a POST request" and put an example of a first line like: "GET /api-endpoint-url HTTP/1.1"

2016-11-08 16:41 UTC, sinelanguage commented on language-examples/remedial-js/2.0-REST/app/exercise.js
> +router.get('/userlist', function(req, res) {
Love it, will do.. thx for the suggestion

2016-11-09 19:12 UTC, sinelanguage commented on language-examples/remedial-js/1.0-http-requests/index.html
> +        <li>initial line, different for request vs. response</li>
Done, will be in next PR

2016-11-09 19:36 UTC, sinelanguage commented on language-examples/remedial-js/2.0-REST/app/exercise.js
> +router.get('/userlist', function(req, res) {
Completed for next PR

2016-11-10 02:27 UTC, winkerVSbecks approved these changes

2016-11-10 02:27 UTC, winkerVSbecks commented
:shipit:

2016-11-10 02:30 UTC, merged